# Generated by Django 5.0.1 on 2024-01-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0005_address_author_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["street", "postal_code", "city"],
                "verbose_name": "Address",
                "verbose_name_plural": "Address Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title", "rating", "author", "is_bestselling"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={("street", "postal_code", "city")},
        ),
        migrations.AddField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(blank=True, to="book_outlet.country"),
        ),
    ]
