# Generated by Django 5.0.1 on 2024-01-10 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
        migrations.RemoveField(
            model_name="tag",
            name="caption",
        ),
        migrations.AddField(
            model_name="tag",
            name="caption",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
